name: Packer

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'config/packer.json'
      - 'config/fontmap.txt'
      - 'projects/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure Git to allow longer paths
        run: git config --system core.longpaths true
        
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          
      - name: Build Packer
        run: dotnet publish .\src\Packer\Packer.csproj -o ./ -r win-x64 -p:PublishSingleFile=true

      - name: Run Packer for each version
        run: |
          for /D %%V in (projects\*) do (
            .\Packer --version="%%~nxV"
            if errorlevel 1 exit /b %errorlevel%
          )
        shell: cmd

      - name: Create timestamp
        id: create_timestamp
        run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%S')"
        shell: bash

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: Snapshot-${{ steps.create_timestamp.outputs.timestamp }}
          title: 中文資源包-Snapshot-${{ steps.create_timestamp.outputs.timestamp }}
          files: |
            projects/Minecraft-Mod-Language-Package-*.zip
